# Generated by Django 2.1.3 on 2018-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20181214_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residual_amount',
            field=models.IntegerField(default=0),
        ),
    ]
