# Generated by Django 2.1.3 on 2018-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_user_residual_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_invested',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='residual_amount',
            field=models.FloatField(default=0),
        ),
    ]
